version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - yarn
  build:
    commands:
      - yarn workspace backend deploy:${DEPLOY_ENV}
      - yarn workspace frontend deploy:${DEPLOY_ENV}
