version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn
  build:
    commands:
      - yarn workspace api deploy:${DEPLOY_ENV}
      - yarn workspace javascript-sdk deploy:${DEPLOY_ENV}
