service: api
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultStage}
  memorySize: 512
  timeout: 10
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    # metrics: true # Enable if you need
    cors: true

custom:
  defaultStage: dev
  defaultRegion: ap-northeast-1
  bundle:
    packager: yarn
    tsConfig: ./tsconfig.json
    caching: false
    linting: false
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
  dotenv:
    path: ../../env

functions:
  app:
    handler: src/handler.handler
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"

package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-bundle
  - serverless-offline
